const datas: any = {
  WORLD: [
    {
      countryName: "Afghanistan",
      continent: "Asia",
      dialCode: "+93",
      iso2: "AF",
      iso3: "AFG",
      currencyCode: "AFN",
      Flag: "../assets/",
    },
    {
      countryName: "Albania",
      continent: "Europe",
      dialCode: "+355",
      iso2: "ALB",
      iso3: "AFG",
      currencyCode: "ALL",
      Flag: "../assets/",
    },
    {
      countryName: "Algeria",
      continent: "Africa",
      dialCode: "+213",
      iso2: "DZ",
      iso3: "DZA",
      currencyCode: "DZD",
      Flag: "../assets/",
    },
    {
      countryName: "Andorra",
      continent: "Europe",
      dialCode: "+376",
      iso2: "AD",
      iso3: "AND",
      currencyCode: "EUR",
      Flag: "../assets/",
    },
    {
      countryName: "Angola",
      continent: "Africa",
      dialCode: "+244",
      iso2: "AO",
      iso3: "AGO",
      currencyCode: "AOA",
      Flag: "../assets/",
    },
    {
      countryName: "Antigua and Barbuda",
      continent: "North America",
      dialCode: "+1",
      iso2: "AG",
      iso3: "ATG",
      currencyCode: "XCD",
      Flag: "../assets/",
    },
    {
      countryName: "Argentina",
      continent: "South America",
      dialCode: "+54",
      iso2: "AR",
      iso3: "ARG",
      currencyCode: "ARS",
      Flag: "../assets/",
    },
    {
      countryName: "Armenia",
      continent: "Asia",
      dialCode: "+374",
      iso2: "AM",
      iso3: "ARM",
      currencyCode: "AMD",
      Flag: "../assets/",
    },
    {
      countryName: "Australia",
      dialCode: "+61",
      iso2: "AU",
      iso3: "AUS",
      currencyCode: "AUD",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Austria",
      dialCode: "+43",
      iso2: "AT",
      iso3: "AUT",
      currencyCode: "AUD",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Azerbaijan",
      dialCode: "+994",
      iso2: "AZ",
      iso3: "AZE",
      currencyCode: "AZN",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Bahamas",
      dialCode: "+1",
      iso2: "BS",
      iso3: "BHS",
      currencyCode: "BSD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Bahrain",
      dialCode: "+973",
      iso2: "BS",
      iso3: "BHS",
      currencyCode: "BHD",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Bangladesh",
      dialCode: "+880",
      iso2: "BD",
      iso3: "BGD",
      currencyCode: "BDT",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Barbados",
      dialCode: "+1246",
      iso2: "BB",
      iso3: "BRB",
      currencyCode: "BBD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Belarus",
      dialCode: "+375",
      iso2: "BY",
      iso3: "BLR",
      currencyCode: "BYN",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Belgium",
      dialCode: "+32",
      iso2: "BE",
      iso3: "BEL",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Belize",
      dialCode: "+501",
      iso2: "BZ",
      iso3: "BLZ",
      currencyCode: "BZD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Benin",
      dialCode: "+229",
      iso2: "BJ",
      iso3: "BEN",
      currencyCode: "XOF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Bhutan",
      dialCode: "+975",
      iso2: "BT",
      iso3: "BTN",
      currencyCode: "BTN",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Bolivia",
      dialCode: "+591",
      iso2: "BO",
      iso3: "BOL",
      currencyCode: "BOV",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "Bosnia and Herzegovina",
      dialCode: "+387",
      iso2: "BA",
      iso3: "BIH",
      currencyCode: "BAM",
      Flag: "../assets/",
    },
    {
      countryName: "Botswana",
      dialCode: "+267",
      iso2: "BW",
      iso3: "BWA",
      currencyCode: "BWP",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Brazil",
      dialCode: "+55",
      iso2: "BR",
      iso3: "BRA",
      currencyCode: "BRL",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "Brunei",
      dialCode: "+673",
      iso2: "BN",
      iso3: "BND",
      currencyCode: "BRL",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Bulgaria",
      dialCode: "+359",
      iso2: "BG",
      iso3: "BGR",
      currencyCode: "BGN",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Burkina Faso",
      dialCode: "+226",
      iso2: "BF",
      iso3: "BFA",
      currencyCode: "XOF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Burundi",
      dialCode: "+257",
      iso2: "BI",
      iso3: "BDI",
      currencyCode: "BIF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: ["Côte d'Ivoire", "Ivory Coast"],
      dialCode: "+225",
      iso2: "CI",
      iso3: "CIV",
      currencyCode: "XOF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Cabo Verde",
      dialCode: "+238",
      iso2: "CV",
      iso3: "CPV",
      currencyCode: "CVE",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Cambodia",
      dialCode: "+855",
      iso2: "KH",
      iso3: "KHM",
      currencyCode: "KHR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Cameroon",
      dialCode: "+237",
      iso2: "CM",
      iso3: "CMR",
      currencyCode: "XAF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Canada",
      dialCode: "+1",
      iso2: "CA",
      iso3: "CAN",
      currencyCode: "CAD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Central African Republic",
      dialCode: "+236",
      iso2: "CF",
      iso3: "CAF",
      currencyCode: "XAF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Chad",
      dialCode: "+235",
      iso2: "TD",
      iso3: "TCD",
      currencyCode: "XAF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Chile",
      dialCode: "+56",
      iso2: "CL",
      iso3: "CHL",
      currencyCode: "CLF",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "China",
      dialCode: "+86",
      iso2: "CN",
      iso3: "CHN",
      currencyCode: "CNY",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Colombia",
      dialCode: "+57",
      iso2: "CO",
      iso3: "COL",
      currencyCode: "COP",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "Comoros",
      dialCode: "+269",
      iso2: "KM",
      iso3: "COM",
      currencyCode: "KMF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Congo",
      dialCode: "+242",
      iso2: "CG",
      iso3: "COG",
      currencyCode: "XAF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Costa Rica",
      dialCode: "+506",
      iso2: "CR",
      iso3: "CRI",
      currencyCode: "CRC",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Croatia",
      dialCode: "+385",
      iso2: "HR",
      iso3: "HRV",
      currencyCode: "HRK",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Cuba",
      dialCode: "+53",
      iso2: "CU",
      iso3: "CUB",
      currencyCode: "CUC",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Cyprus",
      dialCode: "+357",
      iso2: "CY",
      iso3: "CYP",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Czechia (Czech Republic)",
      dialCode: "+420",
      iso2: "CZ",
      iso3: "CZE",
      currencyCode: "CZK",
      Flag: "../assets/",
    },
    {
      countryName: "Democratic Republic of the Congo",
      dialCode: "+243",
      iso2: "CD",
      iso3: "COD",
      currencyCode: "CDF",
      Flag: "../assets/",
    },
    {
      countryName: "Denmark",
      dialCode: "+45",
      iso2: "DK",
      iso3: "DNK",
      currencyCode: "DKK",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Djibouti",
      dialCode: "+253",
      iso2: "DJ",
      iso3: "DJI",
      currencyCode: "DJF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Dominica",
      dialCode: "+1767",
      iso2: "DM",
      iso3: "DMA",
      currencyCode: "XCD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Dominican Republic",
      dialCode: ["1809", " 1829", "1849"],
      iso2: "DO",
      iso3: "DOM",
      currencyCode: "DOP",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Ecuador",
      dialCode: "+593",
      iso2: "EC",
      iso3: "ECU",
      currencyCode: "USD",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "Egypt",
      dialCode: "+20",
      iso2: "EG",
      iso3: "EGY",
      currencyCode: "EGP",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "El Salvador",
      dialCode: "+503",
      iso2: "SV",
      iso3: "SLV",
      currencyCode: "SVC",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Equatorial Guinea",
      dialCode: "+240",
      iso2: "GQ",
      iso3: "GNQ",
      currencyCode: "XAF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Eritrea",
      dialCode: "+291",
      iso2: "ER",
      iso3: "ERI",
      currencyCode: "ERN",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Estonia",
      dialCode: "+372",
      iso2: "EE",
      iso3: "EST",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: ["Eswatini", "Swaziland"],
      dialCode: "+268",
      iso2: "SZ",
      iso3: "SWZ",
      currencyCode: "SZL",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Ethiopia",
      dialCode: "+251",
      iso2: "ET",
      iso3: "ETH",
      currencyCode: "ETB",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Fiji",
      dialCode: "+679",
      iso2: "FJ",
      iso3: "FJI",
      currencyCode: "FJD",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Finland",
      dialCode: "+358",
      iso2: "FI",
      iso3: "FIN",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "France",
      dialCode: "+33",
      iso2: "FR",
      iso3: "FRA",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Gabon",
      dialCode: "+241",
      iso2: "GA",
      iso3: "GAB",
      currencyCode: "XAF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Gambia",
      dialCode: "+220",
      iso2: "GM",
      iso3: "GMB",
      currencyCode: "GMD",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Georgia",
      dialCode: "+995",
      iso2: "GE",
      iso3: "GEO",
      currencyCode: "GEL",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Germany",
      dialCode: "+49",
      iso2: "DE",
      iso3: "DEU",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Ghana",
      dialCode: "+233",
      iso2: "GH",
      iso3: "GHA",
      currencyCode: "GHS",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Greece",
      dialCode: "+30",
      iso2: "GR",
      iso3: "GRC",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Grenada",
      dialCode: "+1473",
      iso2: "GD",
      iso3: "GRD",
      currencyCode: "XCD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Guatemala",
      dialCode: "+502",
      iso2: "GT",
      iso3: "GTM",
      currencyCode: "GTQ",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Guinea",
      dialCode: "+224",
      iso2: "GN",
      iso3: "GIN",
      currencyCode: "GNF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Guinea-Bissau",
      dialCode: "+245",
      iso2: "GW",
      iso3: "GNB",
      currencyCode: "XOF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Guyana",
      dialCode: "+592",
      iso2: "GY",
      iso3: "GUY",
      currencyCode: "GYD",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "Haiti",
      dialCode: "+509",
      iso2: "HT",
      iso3: "HTI",
      currencyCode: "HTG",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Holy See",
      dialCode: "+379",
      iso2: "VA",
      iso3: "VAT",
      currencyCode: "EUR",
      Flag: "../assets/",
    },
    {
      countryName: "Honduras",
      dialCode: "+504",
      iso2: "HN",
      iso3: "HND",
      currencyCode: "HNL",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Hong Kong",
      dialCode: "+852",
      iso2: "HK",
      iso3: "HKG",
      currencyCode: "HKD",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Hungary",
      dialCode: "+36",
      iso2: "HU",
      iso3: "HUN",
      currencyCode: "HUF",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Iceland",
      dialCode: "+354",
      iso2: "IS",
      iso3: "ISL",
      currencyCode: "ISK",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "India",
      dialCode: "+91",
      iso2: "IN",
      iso3: "IND",
      currencyCode: "INR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Indonesia",
      dialCode: "+62",
      iso2: "ID",
      iso3: "IDN",
      currencyCode: "IDR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Iran",
      dialCode: "+98",
      iso2: "IR",
      iso3: "IRN",
      currencyCode: "IRR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Iraq",
      dialCode: "+964",
      iso2: "IQ",
      iso3: "IRQ",
      currencyCode: "IQD",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Ireland",
      dialCode: "+353",
      iso2: "IE",
      iso3: "IRL",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Italy",
      dialCode: "+39",
      iso2: "IT",
      iso3: "ITA",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Jamaica",
      dialCode: "+1876",
      iso2: "JM",
      iso3: "JAM",
      currencyCode: "JMD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Japan",
      dialCode: "+81",
      iso2: "JP",
      iso3: "JPN",
      currencyCode: "JPY",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Jordan",
      dialCode: "+962",
      iso2: "JO",
      iso3: "JOR",
      currencyCode: "JOD",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Kazakhstan",
      dialCode: "+7",
      iso2: "KZ",
      iso3: "KAZ",
      currencyCode: "KZT",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Kenya",
      dialCode: "+254",
      iso2: "KE",
      iso3: "KEN",
      currencyCode: "KES",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Kiribati",
      dialCode: "+686",
      iso2: "KI",
      iso3: "KIR",
      currencyCode: "AUD",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Kuwait",
      dialCode: "+965",
      iso2: "KW",
      iso3: "KIR",
      currencyCode: "KWT",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Kyrgyzstan",
      dialCode: "+996",
      iso2: "KG",
      iso3: "KGZ",
      currencyCode: "KGS",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Laos",
      dialCode: "+856",
      iso2: "LA",
      iso3: "LAO",
      currencyCode: "LAK",
      Flag: "../assets/",
    },
    {
      countryName: "Latvia",
      dialCode: "+371",
      iso2: "LV",
      iso3: "LVA",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Lebanon",
      dialCode: "+961",
      iso2: "LB",
      iso3: "LBN",
      currencyCode: "LBP",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Lesotho",
      dialCode: "+266",
      iso2: "LS",
      iso3: "LSO",
      currencyCode: "LSL",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Liberia",
      dialCode: "+231",
      iso2: "LR",
      iso3: "LBR",
      currencyCode: "LRD",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Libya",
      dialCode: "+218",
      iso2: "LY",
      iso3: "LBY",
      currencyCode: "LYD",
      Flag: "../assets/",
    },
    {
      countryName: "Liechtenstein",
      dialCode: "+423",
      iso2: "LI",
      iso3: "LIE",
      currencyCode: "CHF",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Lithuania",
      dialCode: "+370",
      iso2: "LT",
      iso3: "LTU",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Luxembourg",
      dialCode: "+352",
      iso2: "LU",
      iso3: "LUX",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Macau",
      dialCode: "+853",
      iso2: "MO",
      iso3: "MAC",
      currencyCode: "MOP",
      Flag: "../assets/",
    },
    {
      countryName: "Macedonia",
      dialCode: "+389",
      iso2: "MK",
      iso3: "MKD",
      currencyCode: "MKD",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Madagascar",
      dialCode: "+261",
      iso2: "MG",
      iso3: "MDG",
      currencyCode: "MGA",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Malawi",
      dialCode: "+265",
      iso2: "MW",
      iso3: "MWI",
      currencyCode: "MWK",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Malaysia",
      dialCode: "+60",
      iso2: "MY",
      iso3: "MYS",
      currencyCode: "MYR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Maldives",
      dialCode: "+960",
      iso2: "MV",
      iso3: "MDV",
      currencyCode: "MVR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Mali",
      dialCode: "+223",
      iso2: "ML",
      iso3: "MLI",
      currencyCode: "XOF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Malta",
      dialCode: "+356",
      iso2: "MT",
      iso3: "MLT",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Marshall Islands",
      dialCode: "+692",
      iso2: "MH",
      iso3: "MHL",
      currencyCode: "USD",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Mauritania",
      dialCode: "+222",
      iso2: "MR",
      iso3: "MRT",
      currencyCode: "MRU",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Mauritius",
      dialCode: "+230",
      iso2: "MU",
      iso3: "MUS",
      currencyCode: "MUR",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "MAYOTTE",
      dialCode: "+262",
      iso2: "YT",
      iso3: "MYT",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Mexico",
      dialCode: "+52",
      iso2: "MX",
      iso3: "MEX",
      currencyCode: "MXN",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Micronesia",
      dialCode: "+691",
      iso2: "FM",
      iso3: "FSM",
      currencyCode: "USD",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Moldova",
      dialCode: "+373",
      iso2: "MD",
      iso3: "MDA",
      currencyCode: "MDL",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Monaco",
      dialCode: "+377",
      iso2: "MC",
      iso3: "MCO",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Mongolia",
      dialCode: "+976",
      iso2: "MN",
      iso3: "MNG",
      currencyCode: "MNT",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Montenegro",
      dialCode: "+382",
      iso2: "ME",
      iso3: "MNE",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Montserrat",
      dialCode: "+1664",
      iso2: "MS",
      iso3: "MSR",
      currencyCode: "XCD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Morocco",
      dialCode: "+212",
      iso2: "MA",
      iso3: "MAR",
      currencyCode: "MAD",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Mozambique",
      dialCode: "+258",
      iso2: "MZ",
      iso3: "MOZ",
      currencyCode: "MZN",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Myanmar",
      dialCode: "+95",
      iso2: "MM",
      iso3: "MMR",
      currencyCode: "MMK",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Namibia",
      dialCode: "+264",
      iso2: "NA",
      iso3: "NAM",
      currencyCode: "NAD",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Nauru",
      dialCode: "+674",
      iso2: "NR",
      iso3: "NRU",
      currencyCode: "AUD",
      Flag: "../assets/",
    },
    {
      countryName: "Nepal",
      dialCode: "+977",
      iso2: "NP",
      iso3: "NPL",
      currencyCode: "NPR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Netherlands",
      dialCode: "+31",
      iso2: "NL",
      iso3: "NLD",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "New Caledonia",
      dialCode: "+687",
      iso2: "NC",
      iso3: "NCL",
      currencyCode: "XPF",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "New Zealand",
      dialCode: "+64",
      iso2: "NZ",
      iso3: "NZL",
      currencyCode: "NZD",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Nicaragua",
      dialCode: "+505",
      iso2: "NI",
      iso3: "NIC",
      currencyCode: "NIO",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Niger",
      dialCode: "+227",
      iso2: "NE",
      iso3: "NER",
      currencyCode: "XOF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Nigeria",
      dialCode: "+234",
      iso2: "NG",
      iso3: "NGA",
      currencyCode: "NGN",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Niue",
      dialCode: "+683",
      iso2: "NU",
      iso3: "NIU",
      currencyCode: "NZD",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "North Korea",
      dialCode: "+850",
      iso2: "KP",
      iso3: "PRK",
      currencyCode: "KPW",
      Flag: "../assets/",
    },
    {
      countryName: "Northern Mariana Islands",
      dialCode: "+1670",
      iso2: "MP",
      iso3: "MNP",
      currencyCode: "USD",
      Flag: "../assets/",
    },
    {
      countryName: "Norway",
      dialCode: "+47",
      iso2: "NO",
      iso3: "NOR",
      currencyCode: "NOK",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Oman",
      dialCode: "+968",
      iso2: "OM",
      iso3: "OMN",
      currencyCode: "OMR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Pakistan",
      dialCode: "+92",
      iso2: "PK",
      iso3: "PAK",
      currencyCode: "PKR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Palau",
      dialCode: "+680",
      iso2: "PW",
      iso3: "PLW",
      currencyCode: "USD",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Palestine",
      dialCode: "+970",
      iso2: "PS",
      iso3: "PSE",
      currencyCode: "ILS",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Panama",
      dialCode: "+507",
      iso2: "PA",
      iso3: "PAN",
      currencyCode: "PAB",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Papua New Guinea",
      dialCode: "+675",
      iso2: "PG",
      iso3: "PNG",
      currencyCode: "PGK",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Paraguay",
      dialCode: "+595",
      iso2: "PY",
      iso3: "PRY",
      currencyCode: "PYG",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "Peru",
      dialCode: "+51",
      iso2: "PE",
      iso3: "PER",
      currencyCode: "PEN",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "Philippines",
      dialCode: "+63",
      iso2: "PH",
      iso3: "PHL",
      currencyCode: "PHP",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Pitcairn",
      dialCode: "+64",
      iso2: "PN",
      iso3: "PCN",
      currencyCode: "NZD",
      Flag: "../assets/",
    },
    {
      countryName: "Poland",
      dialCode: "+48",
      iso2: "PL",
      iso3: "POL",
      currencyCode: "PLN",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Portugal",
      dialCode: "+351",
      iso2: "PT",
      iso3: "PRT",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Puerto Rico",
      dialCode: ["+1787", "+1939"],
      iso2: "PR",
      iso3: "PRI",
      currencyCode: "USD",
      Flag: "../assets/",
    },
    {
      countryName: "Qatar",
      dialCode: "+974",
      iso2: "QA",
      iso3: "QAT",
      currencyCode: "QAR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Reunion",
      dialCode: "+262",
      iso2: "RE",
      iso3: "REU",
      currencyCode: "EUR",
      Flag: "../assets/",
    },
    {
      countryName: "Romania",
      dialCode: "+40",
      iso2: "RO",
      iso3: "ROU",
      currencyCode: "RON",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Russia",
      dialCode: "+7",
      iso2: "RU",
      iso3: "RUS",
      currencyCode: "RUB",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Rwanda",
      dialCode: "+250",
      iso2: "RW",
      iso3: "RWA",
      currencyCode: "RWF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Saint Barthelemy",
      dialCode: "+590",
      iso2: "BL",
      iso3: "BLM",
      currencyCode: "EUR",
      Flag: "../assets/",
    },
    {
      countryName: "Saint Helena",
      dialCode: "+290",
      iso2: "SH",
      iso3: "SHN",
      currencyCode: "SHP",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Saint Kitts and Nevis",
      dialCode: "+1869",
      iso2: "KN",
      iso3: "KNA",
      currencyCode: "XCD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Saint Lucia",
      dialCode: "+1758",
      iso2: "LC",
      iso3: "LCA",
      currencyCode: "XCD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Saint Martin",
      dialCode: "+590",
      iso2: "MF",
      iso3: "MAF",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Saint Pierre and Miquelon",
      dialCode: "+508",
      iso2: "PM",
      iso3: "SPM",
      currencyCode: "EUR",
      Flag: "../assets/",
    },
    {
      countryName: "Saint Vincent and the Grenadines",
      dialCode: "+1784",
      iso2: "VC",
      iso3: "VCT",
      currencyCode: "XCD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Samoa",
      dialCode: "+685",
      iso2: "WS",
      iso3: "WSM",
      currencyCode: "WST",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "San Marino",
      dialCode: "+378",
      iso2: "SM",
      iso3: "SMR",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Sao Tome and Principe",
      dialCode: "+239",
      iso2: "ST",
      iso3: "STP",
      currencyCode: "STN",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Saudi Arabia",
      dialCode: "+966",
      iso2: "SA",
      iso3: "SAU",
      currencyCode: "SAR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Senegal",
      dialCode: "+221",
      iso2: "SN",
      iso3: "SEN",
      currencyCode: "XOF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Serbia",
      dialCode: "+381",
      iso2: "RS",
      iso3: "SRB",
      currencyCode: "RSD",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Seychelles",
      dialCode: "+248",
      iso2: "SC",
      iso3: "SYC",
      currencyCode: "SCR",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Sierra Leone",
      dialCode: "+232",
      iso2: "SL",
      iso3: "SLE",
      currencyCode: "SLL",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Singapore",
      dialCode: "+65",
      iso2: "SG",
      iso3: "SGP",
      currencyCode: "SGD",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Sint Maarten",
      dialCode: "+1721",
      iso2: "SX",
      iso3: "SXM",
      currencyCode: "ANG",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Slovakia",
      dialCode: "+421",
      iso2: "SK",
      iso3: "SVK",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Slovenia",
      dialCode: "+386",
      iso2: "SI",
      iso3: "SVN",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Solomon Islands",
      dialCode: "+677",
      iso2: "SB",
      iso3: "SLB",
      currencyCode: "SBD",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Somalia",
      dialCode: "+252",
      iso2: "SO",
      iso3: "SOM",
      currencyCode: "SOS",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "South Africa",
      dialCode: "+27",
      iso2: "ZA",
      iso3: "ZAF",
      currencyCode: "ZAR",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "South Korea",
      dialCode: "+82",
      iso2: "KR",
      iso3: "KOR",
      currencyCode: "KRW",
      Flag: "../assets/",
    },
    {
      countryName: "South Sudan",
      dialCode: "+211",
      iso2: "SS",
      iso3: "SSD",
      currencyCode: "SSP",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Spain",
      dialCode: "+34",
      iso2: "ES",
      iso3: "ESP",
      currencyCode: "EUR",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Sri Lanka",
      dialCode: "+94",
      iso2: "LK",
      iso3: "LKA",
      currencyCode: "LKR",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Sudan",
      dialCode: "+249",
      iso2: "SD",
      iso3: "SDN",
      currencyCode: "SDG",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Suriname",
      dialCode: "+597",
      iso2: "SR",
      iso3: "SUR",
      currencyCode: "SRD",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "Svalbard and Jan Mayen",
      dialCode: "+47",
      iso2: "SJ",
      iso3: "SJM",
      currencyCode: "NOK",
      Flag: "../assets/",
    },
    {
      countryName: "Sweden",
      dialCode: "+46",
      iso2: "SE",
      iso3: "SWE",
      currencyCode: "SEK",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Switzerland",
      dialCode: "+41",
      iso2: "CH",
      iso3: "CHE",
      currencyCode: "CHE",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "Syria",
      dialCode: "+963",
      iso2: "SY",
      iso3: "SYR",
      currencyCode: "SYP",
      Flag: "../assets/",
    },
    {
      countryName: "Taiwan",
      dialCode: "+886",
      iso2: "TW",
      iso3: "TWN",
      currencyCode: "TWD",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Tajikistan",
      dialCode: "+992",
      iso2: "TJ",
      iso3: "TJK",
      currencyCode: "TJS",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Tanzania",
      dialCode: "+255",
      iso2: "TZ",
      iso3: "TZA",
      currencyCode: "TZS",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Thailand",
      dialCode: "+66",
      iso2: "TH",
      iso3: "THA",
      currencyCode: "THB",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Timor-Leste",
      dialCode: "+670",
      iso2: "TL",
      iso3: "TLS",
      currencyCode: "USD",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Togo",
      dialCode: "+228",
      iso2: "TG",
      iso3: "TGO",
      currencyCode: "XOF",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Tokelau",
      dialCode: "+690",
      iso2: "TK",
      iso3: "TKL",
      currencyCode: "NZD",
      Flag: "../assets/",
    },
    {
      countryName: "Tonga",
      dialCode: "+676",
      iso2: "TO",
      iso3: "TON",
      currencyCode: "TOP",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Trinidad and Tobago",
      dialCode: "+1868",
      iso2: "TT",
      iso3: "TTO",
      currencyCode: "TTD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Tunisia",
      dialCode: "+216",
      iso2: "TN",
      iso3: "TUN",
      currencyCode: "TND",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Turkey",
      dialCode: "+90",
      iso2: "TR",
      iso3: "TUR",
      currencyCode: "TRY",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Turkmenistan",
      dialCode: "+993",
      iso2: "TM",
      iso3: "TKM",
      currencyCode: "TMT",
      Flag: "../assets/",
    },
    {
      countryName: "Turks and Caicos Islands",
      dialCode: "+1649",
      iso2: "TC",
      iso3: "TCA",
      currencyCode: "USD",
      Flag: "../assets/",
      continent: "North America",
    },
    {
      countryName: "Tuvalu",
      dialCode: "+688",
      iso2: "TV",
      iso3: "TUV",
      currencyCode: "AUD",
      Flag: "../assets/",
    },
    {
      countryName: "U.S. Virgin Islands",
      dialCode: "+1340",
      iso2: "VI",
      iso3: "VIR",
      currencyCode: "USD",
      Flag: "../assets/",
    },
    {
      countryName: "Uganda",
      dialCode: "+256",
      iso2: "UG",
      iso3: "UGA",
      currencyCode: "UGX",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Ukraine",
      dialCode: "+380",
      iso2: "UA",
      iso3: "UKR",
      currencyCode: "UAH",
      Flag: "../assets/",
      continent: "Europe",
    },
    {
      countryName: "United Arab Emirates",
      dialCode: "+971",
      iso2: "AE",
      iso3: "ARE",
      currencyCode: "AED",
      Flag: "../assets/",
    },
    {
      countryName: "United Kingdom",
      dialCode: "+44",
      iso2: "GB",
      iso3: "GBR",
      currencyCode: "GBP",
      Flag: "../assets/",
    },
    {
      countryName: "United States of America",
      dialCode: "+1",
      iso2: "US",
      iso3: "USA",
      currencyCode: "USD",
      Flag: "../assets/",
    },
    {
      countryName: "Uruguay",
      dialCode: "+598",
      iso2: "UY",
      iso3: "URY",
      currencyCode: "UYI",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "Uzbekistan",
      dialCode: "+998",
      iso2: "UZ",
      iso3: "UZB",
      currencyCode: "UZS",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Vanuatu",
      dialCode: "+678",
      iso2: "VU",
      iso3: "VUT",
      currencyCode: "VUV",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Vatican",
      dialCode: "+379",
      iso2: "VA",
      iso3: "VAT",
      currencyCode: "EUR",
      Flag: "../assets/",
    },
    {
      countryName: "Venezuela",
      dialCode: "+58",
      iso2: "VE",
      iso3: "VEN",
      currencyCode: "VEF",
      Flag: "../assets/",
      continent: "South America",
    },
    {
      countryName: "Vietnam",
      dialCode: "+84",
      iso2: "VN",
      iso3: "VNM",
      currencyCode: "VND",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Wallis and Futuna",
      dialCode: "+681",
      iso2: "WF",
      iso3: "WLF",
      currencyCode: "XPF",
      Flag: "../assets/",
      continent: "Australia-Oceania",
    },
    {
      countryName: "Western Sahara",
      dialCode: "+212",
      iso2: "EH",
      iso3: "ESH",
      currencyCode: "MAD",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Yemen",
      dialCode: "+967",
      iso2: "YE",
      iso3: "YEM",
      currencyCode: "YER",
      Flag: "../assets/",
      continent: "Asia",
    },
    {
      countryName: "Zambia",
      dialCode: "+260",
      iso2: "ZM",
      iso3: "ZMB",
      currencyCode: "ZMW",
      Flag: "../assets/",
      continent: "Africa",
    },
    {
      countryName: "Zimbabwe",
      dialCode: "+263",
      iso2: "ZW",
      iso3: "ZWE",
      currencyCode: "ZWL",
      Flag: "../assets/",
      continent: "Africa",
    },
  ],
}
export default datas
